kotlin.code.style=official

pluginGroup=com.github.alexBlakeGoudemond.Kudos
pluginName=Kudos
pluginVersion=1.0.0
pluginRepositoryUrl=https://github.com/alexBlakeGoudemond/jetbrains-kudos

# Supported build number ranges and IntelliJ Platform versions -> https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
pluginSinceBuild=251
